version: '3.1'

services:

    wordpress:
        image: wordpress:5.9.3
        restart: always
        working_dir: /var/www/html
        ports:
            - 80:80
        environment:
            WORDPRESS_DB_HOST: database
            WORDPRESS_DB_USER: exampleuser
            WORDPRESS_DB_PASSWORD: examplepass
            WORDPRESS_DB_NAME: exampledb
        volumes:
            - ./wp:/var/www/html

    database:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: exampledb
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: examplepass
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
          - db:/var/lib/mysql
          - ./wp/wp-content/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql:ro

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=database
            - PMA_USER=exampleuser
            - PMA_PASSWORD=examplepass

    wpcli:
        depends_on:
            - database
            - wordpress
        image: wordpress:cli
        working_dir: /var/www/html
        user: xfs
        volumes:
            - ./wp:/var/www/html
        environment:
            WORDPRESS_DB_HOST: database
            WORDPRESS_DB_USER: exampleuser
            WORDPRESS_DB_PASSWORD: examplepass
            WORDPRESS_DB_NAME: exampledb

volumes:
    db:
